export type SchemaSeverity = 'critical' | 'high' | 'medium' | 'low';

export interface SchemaContract {
  id: string;
  pageType: string;
  templatePath: string;
  sampleUrls: string[];
  requiredTypes: string[];
  recommendedTypes: string[];
  missingSeverity: SchemaSeverity;
}

export const SCHEMA_CONTRACTS: SchemaContract[] = [
  {
    id: 'home',
    pageType: 'Home',
    templatePath: 'app/page.tsx',
    sampleUrls: ['/'],
    requiredTypes: ['OnlineStore', 'WebSite', 'WebPage'],
    recommendedTypes: ['FAQPage'],
    missingSeverity: 'high',
  },
  {
    id: 'product-canonical',
    pageType: 'Product (canonical)',
    templatePath: 'app/products/[handle]/page.tsx',
    sampleUrls: ['/products/sample-product'],
    requiredTypes: ['Product', 'BreadcrumbList'],
    recommendedTypes: ['AggregateRating', 'Offer', 'AggregateOffer'],
    missingSeverity: 'critical',
  },
  {
    id: 'product-catch-all',
    pageType: 'Product (catch-all)',
    templatePath: 'app/[...slug]/page.tsx',
    sampleUrls: ['/horse/rugs/turnout/sample-product'],
    requiredTypes: ['Product', 'BreadcrumbList'],
    recommendedTypes: ['AggregateRating', 'Offer', 'AggregateOffer'],
    missingSeverity: 'critical',
  },
  {
    id: 'category-fallback-product',
    pageType: 'Product (category fallback)',
    templatePath: 'app/[category]/page.tsx',
    sampleUrls: ['/sample-product'],
    requiredTypes: ['Product'],
    recommendedTypes: ['AggregateRating', 'Offer', 'AggregateOffer'],
    missingSeverity: 'critical',
  },
  {
    id: 'collection-category',
    pageType: 'Collection (category)',
    templatePath: 'app/[category]/page.tsx',
    sampleUrls: ['/horse'],
    requiredTypes: ['CollectionPage', 'ItemList', 'BreadcrumbList'],
    recommendedTypes: ['FAQPage'],
    missingSeverity: 'high',
  },
  {
    id: 'collection-subcategory',
    pageType: 'Collection (subcategory)',
    templatePath: 'app/[category]/[subcategory]/page.tsx',
    sampleUrls: ['/horse/rugs'],
    requiredTypes: ['CollectionPage', 'ItemList', 'BreadcrumbList'],
    recommendedTypes: ['FAQPage'],
    missingSeverity: 'high',
  },
  {
    id: 'collection-sub-subcategory-or-product',
    pageType: 'Collection or Product (third level)',
    templatePath: 'app/[category]/[subcategory]/[product]/page.tsx',
    sampleUrls: ['/sample-third-level', '/horse/rugs/turnout/sample-product'],
    requiredTypes: ['BreadcrumbList'],
    recommendedTypes: ['CollectionPage', 'ItemList', 'Product'],
    missingSeverity: 'high',
  },
  {
    id: 'sale-collection',
    pageType: 'Collection (on-sale)',
    templatePath: 'app/on-sale/page.tsx',
    sampleUrls: ['/on-sale'],
    requiredTypes: ['CollectionPage', 'ItemList', 'BreadcrumbList'],
    recommendedTypes: [],
    missingSeverity: 'high',
  },
  {
    id: 'brand-detail',
    pageType: 'Brand Collection',
    templatePath: 'app/brands/[handle]/page.tsx',
    sampleUrls: ['/brands/sample-brand'],
    requiredTypes: ['CollectionPage', 'ItemList', 'BreadcrumbList'],
    recommendedTypes: [],
    missingSeverity: 'medium',
  },
  {
    id: 'brand-index',
    pageType: 'Brand Index',
    templatePath: 'app/brands/page.tsx',
    sampleUrls: ['/brands'],
    requiredTypes: ['CollectionPage', 'ItemList'],
    recommendedTypes: ['Brand'],
    missingSeverity: 'medium',
  },
  {
    id: 'faq-page',
    pageType: 'FAQ',
    templatePath: 'app/faq/page.tsx',
    sampleUrls: ['/faq'],
    requiredTypes: ['FAQPage'],
    recommendedTypes: ['WebPage'],
    missingSeverity: 'high',
  },
  {
    id: 'about-page',
    pageType: 'About',
    templatePath: 'app/about/page.tsx',
    sampleUrls: ['/about'],
    requiredTypes: ['AboutPage', 'Organization'],
    recommendedTypes: ['LocalBusiness'],
    missingSeverity: 'medium',
  },
  {
    id: 'contact-page',
    pageType: 'Contact',
    templatePath: 'app/contact/page.tsx',
    sampleUrls: ['/contact'],
    requiredTypes: ['ContactPage', 'Organization'],
    recommendedTypes: ['ContactPoint'],
    missingSeverity: 'medium',
  },
  {
    id: 'news-index',
    pageType: 'News Index',
    templatePath: 'app/news/page.tsx',
    sampleUrls: ['/news'],
    requiredTypes: ['Blog', 'CollectionPage'],
    recommendedTypes: ['BlogPosting'],
    missingSeverity: 'medium',
  },
  {
    id: 'news-article',
    pageType: 'News Article',
    templatePath: 'app/news/[handle]/page.tsx',
    sampleUrls: ['/news/sample-article'],
    requiredTypes: ['BlogPosting'],
    recommendedTypes: ['Person'],
    missingSeverity: 'medium',
  },
  {
    id: 'news-author',
    pageType: 'News Author',
    templatePath: 'app/news/author/[slug]/page.tsx',
    sampleUrls: ['/news/author/sample-author'],
    requiredTypes: ['ProfilePage', 'Person'],
    recommendedTypes: ['ItemList'],
    missingSeverity: 'medium',
  },
  {
    id: 'privacy-policy',
    pageType: 'Policy (privacy)',
    templatePath: 'app/privacy-policy/page.tsx',
    sampleUrls: ['/privacy-policy'],
    requiredTypes: ['WebPage'],
    recommendedTypes: ['Organization'],
    missingSeverity: 'low',
  },
  {
    id: 'terms-policy',
    pageType: 'Policy (terms)',
    templatePath: 'app/terms-of-service/page.tsx',
    sampleUrls: ['/terms-of-service'],
    requiredTypes: ['WebPage'],
    recommendedTypes: ['Organization'],
    missingSeverity: 'low',
  },
  {
    id: 'shipping-policy',
    pageType: 'Policy (shipping)',
    templatePath: 'app/shipping-delivery/page.tsx',
    sampleUrls: ['/shipping-delivery'],
    requiredTypes: ['WebPage'],
    recommendedTypes: ['Organization'],
    missingSeverity: 'low',
  },
  {
    id: 'returns-policy',
    pageType: 'Policy (returns)',
    templatePath: 'app/returns-refunds/page.tsx',
    sampleUrls: ['/returns-refunds'],
    requiredTypes: ['WebPage'],
    recommendedTypes: ['Organization'],
    missingSeverity: 'low',
  },
  {
    id: 'search-page',
    pageType: 'Search',
    templatePath: 'app/search/page.tsx',
    sampleUrls: ['/search'],
    requiredTypes: ['SearchResultsPage'],
    recommendedTypes: ['SearchAction'],
    missingSeverity: 'low',
  },
  {
    id: 'reviews-page',
    pageType: 'Reviews',
    templatePath: 'app/reviews/page.tsx',
    sampleUrls: ['/reviews'],
    requiredTypes: ['WebPage'],
    recommendedTypes: ['Organization'],
    missingSeverity: 'low',
  },
  {
    id: 'review-page',
    pageType: 'Write Review',
    templatePath: 'app/review/page.tsx',
    sampleUrls: ['/review'],
    requiredTypes: ['WebPage'],
    recommendedTypes: ['Organization'],
    missingSeverity: 'low',
  },
];
