import type { MetadataRoute } from 'next';
import { getCanonicalSiteUrl } from '@/lib/seo/site-url';

const ENTITYMAP_PATHS = ['/entitymap.json', '/entitymap.html'] as const;

const GOOGLE_CRAWLER_ALLOW = [
  ...ENTITYMAP_PATHS,
  '/',
  '/products/',
  '/collections/',
  '/horse/',
  '/rider/',
  '/dog/',
  '/pet/',
  '/brands/',
] as const;

/** Facet/tracking params only. Do not block `?variant=` — GMC landing pages use it. */
const GOOGLE_CRAWLER_DISALLOW = [
  '/api/',
  '/preview',
  '/admin',
  '/account',
  '/cart',
  '/checkout',
  '/orders',
  '/search',
  '/*+*',
  '/*%2B*',
  '/*.atom',
  '/*.rss',
  '/*.json',
  '/*globo*',
  '/*secomapp*',
  '/*toolbox*',
  '/*?*utm_*',
  '/*?*ref=*',
  '/*?*fbclid=*',
  '/*?*gclid=*',
  '/*?*size=*',
  '/*?*price=*',
  '/*?*color=*',
  '/*?*colour=*',
  '/*?*brand=*',
  '/*?*sort=*',
  '/*?*sort_by=*',
  '/*?*page=*',
  '/*?filter*',
] as const;

export default function robots(): MetadataRoute.Robots {
  const baseUrl = getCanonicalSiteUrl();

  return {
    rules: [
      // Own group: GSC URL Inspection only. Does not affect Search or GMC.
      {
        userAgent: 'Google-InspectionTool',
        allow: ['/', '/*?*variant=*'],
      },
      {
        userAgent: ['Googlebot', 'Googlebot-Image', 'AdsBot-Google', 'AdsBot-Google-Mobile'],
        allow: ['/*?*variant=*', ...GOOGLE_CRAWLER_ALLOW],
        disallow: [...GOOGLE_CRAWLER_DISALLOW],
      },

      {
        userAgent: 'Bingbot',
        allow: [...GOOGLE_CRAWLER_ALLOW],
        disallow: [
          '/api/',
          '/_next/',
          '/preview',
          '/admin',
          '/account',
          '/cart',
          '/checkout',
          '/orders',
          '/search',
          '/*+*',
          '/*%2B*',
          '/*.atom',
          '/*.rss',
          '/*.json',
          '/*globo*',
          '/*secomapp*',
          '/*toolbox*',
          '/*?*utm_*',
          '/*?*ref=*',
          '/*?*fbclid=*',
          '/*?*gclid=*',
          '/*?*size=*',
          '/*?*price=*',
          '/*?*color=*',
          '/*?*colour=*',
          '/*?*brand=*',
          '/*?*sort=*',
          '/*?*sort_by=*',
          '/*?*variant=*',
          '/*?*page=*',
          '/*?filter*',
        ],
      },

      {
        userAgent: '*',
        allow: [
          '/*?*variant=*',
          ...ENTITYMAP_PATHS,
          '/',
          '/products/',
          '/collections/',
        ],
        disallow: [
          '/api/',
          '/_next/',
          '/preview',
          '/admin',
          '/account',
          '/cart',
          '/checkout',
          '/orders',
          '/404',
          '/500',
          '/pages/',
          '/blogs/*/tagged/*',
          '/*+*',
          '/*%2B*',
          '/*.atom',
          '/*.rss',
          '/*.json',
          '/*globo*',
          '/*secomapp*',
          '/*toolbox*',
          '/search',
          '/*?q=*',
          '/*?*size=*',
          '/*?*price=*',
          '/*?*color=*',
          '/*?*colour=*',
          '/*?*brand=*',
          '/*?*sort=*',
          '/*?*sort_by=*',
          '/*?*limit=*',
          '/*?*page=*',
          '/*?filter*',
          '/*?*utm_*',
          '/*?*ref=*',
          '/*?*fbclid=*',
          '/*?*gclid=*',
          '/*?*mc_*',
          '/*?*_ga=*',
          '/*?*_ke=*',
          '/*?*_pos=*',
          '/*?*_psq=*',
          '/*?*_ss=*',
          '/*?*_v=*',
          '/*?*discount=*',
          '/*/print',
          '/*?print=*',
          '/*?share=*',
        ],
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
  };
}
