#!/usr/bin/env tsx
/**
 * AI-Powered Collection Content Generator
 * 
 * This script:
 * 1. Reads mapping-template-draft2.csv to get all category paths
 * 2. Calls OpenAI to generate SEO-optimized content
 * 3. Executes SQL to insert/update content in database
 * 4. Supports dry-run mode and progress tracking
 * 
 * Run: npm run content:generate
 * Dry run: npm run content:generate:dry
 */

// Load environment variables first
import { config } from 'dotenv';
import { resolve } from 'path';
config({ path: resolve(process.cwd(), '.env.local') });

import { sql } from '@vercel/postgres';
import OpenAI from 'openai';
import * as fs from 'fs';
import * as path from 'path';
import * as csv from 'csv-parse/sync';

interface MappingRow {
  top_level: string;
  parent_category: string;
  subcategory_handle: string;
  product_type: string;
  action: string;
  merge_to?: string;
  notes?: string;
}

interface CategoryPath {
  urlPath: string;
  categoryName: string;
  parentContext: string;
  level: number;
  parentUrl: string | null;
}

const DRY_RUN = process.env.DRY_RUN === 'true';
const SAMPLE_SIZE = parseInt(process.env.SAMPLE_SIZE || '0', 10);
const TARGET_PATH = process.env.TARGET_PATH || '';

async function generateCollectionContent() {
  console.log('🚀 AI Collection Content Generator\n');
  
  if (DRY_RUN) {
    console.log('⚠️  DRY RUN MODE - No database changes will be made\n');
  }

  if (TARGET_PATH) {
    console.log(`🎯 TARGET MODE - Processing only: ${TARGET_PATH}\n`);
  } else if (SAMPLE_SIZE > 0) {
    console.log(`📊 SAMPLE MODE - Processing only ${SAMPLE_SIZE} categories\n`);
  }

  // Initialize OpenAI
  const openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
  });

  if (!process.env.OPENAI_API_KEY) {
    console.error('❌ OPENAI_API_KEY not found in environment');
    process.exit(1);
  }

  // Load system prompt
  const promptPath = path.join(process.cwd(), 'AI-CONTENT-GENERATION-PROMPT.md');
  if (!fs.existsSync(promptPath)) {
    console.error('❌ AI prompt file not found:', promptPath);
    process.exit(1);
  }
  const systemPrompt = fs.readFileSync(promptPath, 'utf-8');

  // Load mapping CSV
  console.log('📄 Loading category mapping...');
  const mappingPath = path.join(process.cwd(), 'exports', 'mapping-template-draft2.csv');
  const mappingContent = fs.readFileSync(mappingPath, 'utf-8');
  const mappingRows = csv.parse(mappingContent, {
    columns: true,
    skip_empty_lines: true,
    trim: true,
  }) as MappingRow[];

  // Build category paths (only include action)
  const categoryPaths = buildCategoryPaths(mappingRows);
  console.log(`✅ Found ${categoryPaths.length} categories to process\n`);

  // Apply filters (target path or sample size)
  let pathsToProcess = categoryPaths;
  
  if (TARGET_PATH) {
    pathsToProcess = categoryPaths.filter(p => p.urlPath === TARGET_PATH);
    if (pathsToProcess.length === 0) {
      console.error(`❌ Target path not found: ${TARGET_PATH}`);
      process.exit(1);
    }
  } else if (SAMPLE_SIZE > 0) {
    pathsToProcess = categoryPaths.slice(0, SAMPLE_SIZE);
  }

  console.log(`📊 Processing ${pathsToProcess.length} categories...\n`);

  let generated = 0;
  let skipped = 0;
  let errors = 0;

  for (let i = 0; i < pathsToProcess.length; i++) {
    const category = pathsToProcess[i];
    
    console.log(`\n[${i + 1}/${pathsToProcess.length}] ${category.urlPath}`);
    console.log(`   Category: ${category.categoryName}`);
    console.log(`   Level: ${category.level}`);

    try {
      // Check if content already exists (skip if generated by AI)
      if (!DRY_RUN) {
        const existing = await sql.query(
          `SELECT id, generated_by FROM collection_content 
           WHERE url_path = $1 AND generated_by = 'ai-agent'
           LIMIT 1`,
          [category.urlPath]
        );

        if (existing.rows.length > 0) {
          console.log('   ⏭️  Skipping (already generated by AI)');
          skipped++;
          continue;
        }
      }

      // Build user prompt
      const userPrompt = `Generate content for:
- URL Path: ${category.urlPath}
- Category Name: ${category.categoryName}
- Parent Context: ${category.parentContext}
- Category Level: ${category.level}
- Parent URL: ${category.parentUrl || 'null'}`;

      console.log('   🤖 Calling OpenAI...');

      // Call OpenAI
      const response = await openai.chat.completions.create({
        model: 'gpt-4o',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ],
        temperature: 0.7,
        max_tokens: 2000,
      });

      const sqlOutput = response.choices[0].message.content;

      if (!sqlOutput) {
        console.error('   ❌ No output from OpenAI');
        errors++;
        continue;
      }

      // Extract SQL from markdown code blocks if present
      let cleanSQL = sqlOutput;
      const codeBlockMatch = sqlOutput.match(/```sql\n([\s\S]*?)\n```/);
      if (codeBlockMatch) {
        cleanSQL = codeBlockMatch[1];
      }

      if (DRY_RUN) {
        console.log('   ✅ Generated SQL (dry run):');
        console.log('   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
        console.log(cleanSQL);
        console.log('   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
        generated++;
      } else {
        // Execute SQL using @vercel/postgres (supports raw SQL)
        console.log('   💾 Inserting into database...');
        try {
          const result = await sql.query(cleanSQL);
          console.log('   ✅ Inserted successfully');
          console.log(`   📝 Rows affected: ${result.rowCount}`);
          generated++;
        } catch (sqlError) {
          console.error('   ❌ SQL execution failed:');
          console.error('   ', sqlError instanceof Error ? sqlError.message : sqlError);
          console.error('   SQL preview:');
          console.error(cleanSQL.substring(0, 300) + '...');
          errors++;
          // Don't throw - continue with other categories
        }
      }

      // Rate limiting: Wait 1 second between requests to respect OpenAI limits
      if (i < pathsToProcess.length - 1) {
        await new Promise(resolve => setTimeout(resolve, 1000));
      }

    } catch (error) {
      errors++;
      console.error(`   ❌ Error:`, error instanceof Error ? error.message : error);
    }
  }

  console.log('\n\n🎉 Generation complete!');
  console.log(`📊 Stats:`);
  console.log(`   - Total categories: ${pathsToProcess.length}`);
  console.log(`   - Generated: ${generated}`);
  console.log(`   - Skipped: ${skipped}`);
  console.log(`   - Errors: ${errors}`);

  if (!DRY_RUN && generated > 0) {
    console.log('\n🔍 Verifying database...');
    const totalCount = await sql.query('SELECT COUNT(*) as count FROM collection_content');
    const aiCount = await sql.query(`SELECT COUNT(*) as count FROM collection_content WHERE generated_by = 'ai-agent'`);
    const csvCount = await sql.query(`SELECT COUNT(*) as count FROM collection_content WHERE generated_by = 'csv-migration'`);
    console.log(`✅ Total rows in database: ${totalCount.rows[0].count}`);
    console.log(`   - AI-generated: ${aiCount.rows[0].count}`);
    console.log(`   - CSV-migrated: ${csvCount.rows[0].count}`);
  }
}

/**
 * Build category paths from mapping CSV
 */
function buildCategoryPaths(mappingRows: MappingRow[]): CategoryPath[] {
  const paths: CategoryPath[] = [];
  const seen = new Set<string>();

  for (const row of mappingRows) {
    // Only process 'include' rows (skip excludes and merges)
    if (row.action !== 'include') continue;

    // Build URL path from existing structure
    const parts: string[] = [];
    if (row.top_level && row.top_level.trim()) {
      parts.push(row.top_level.trim());
    }
    if (row.parent_category && row.parent_category.trim()) {
      parts.push(row.parent_category.trim());
    }
    if (row.subcategory_handle && row.subcategory_handle.trim()) {
      parts.push(row.subcategory_handle.trim());
    }

    if (parts.length === 0) continue;

    const urlPath = '/' + parts.join('/');
    
    // Skip duplicates
    if (seen.has(urlPath)) continue;
    seen.add(urlPath);

    const level = parts.length;
    
    // Determine parent URL
    let parentUrl: string | null = null;
    if (level === 2) {
      parentUrl = '/' + parts[0];
    } else if (level === 3) {
      parentUrl = '/' + parts.slice(0, 2).join('/');
    }

    paths.push({
      urlPath,
      categoryName: row.product_type,
      parentContext: row.top_level,
      level,
      parentUrl,
    });
  }

  // Sort by level (top-level first, then subcategories, then sub-subcategories)
  paths.sort((a, b) => a.level - b.level);

  return paths;
}

// Run the generator
generateCollectionContent()
  .then(() => {
    console.log('\n✅ Done!');
    process.exit(0);
  })
  .catch((error) => {
    console.error('\n❌ Failed:', error);
    process.exit(1);
  });
