import fs from 'fs';
import path from 'path';
import { parse } from 'csv-parse/sync';

const REDIRECTS_DIR = path.join(process.cwd(), 'redirects');
const OUTPUT_FILE = path.join(process.cwd(), 'lib/redirects/maps.ts');

interface RedirectRow {
  from: string;
  to: string;
}

function parseCsvFile(filename: string): Record<string, string> {
  const filePath = path.join(REDIRECTS_DIR, filename);
  if (!fs.existsSync(filePath)) {
    console.warn(`Warning: Redirect file ${filename} not found.`);
    return {};
  }

  const content = fs.readFileSync(filePath, 'utf-8');
  const records = parse(content, {
    columns: true,
    skip_empty_lines: true,
    trim: true,
  }) as RedirectRow[];

  const map: Record<string, string> = {};
  records.forEach((row) => {
    if (row.from && row.to) {
      // Ensure paths start with / and don't have trailing /
      const fromPath = normalizePath(row.from);
      const toPath = normalizePath(row.to);
      map[fromPath] = toPath;
    }
  });

  return map;
}

function normalizePath(p: string): string {
  if (!p.startsWith('/')) p = '/' + p;
  if (p.length > 1 && p.endsWith('/')) p = p.slice(0, -1);
  return p;
}

function generateRedirects() {
  console.log('Generating redirect maps...');

  const collections = parseCsvFile('collections.csv');
  const blogs = parseCsvFile('blogs.csv');
  const pages = parseCsvFile('pages.csv');

  const content = `// This file is auto-generated by scripts/generate-redirects.ts
// Do not edit this file manually.

export const collectionRedirects: Record<string, string> = ${JSON.stringify(collections, null, 2)};

export const blogRedirects: Record<string, string> = ${JSON.stringify(blogs, null, 2)};

export const pageRedirects: Record<string, string> = ${JSON.stringify(pages, null, 2)};
`;

  fs.writeFileSync(OUTPUT_FILE, content);
  console.log(`Redirect maps written to ${OUTPUT_FILE}`);
}

generateRedirects();





